version: '2'

services:
  influxdb:
    image: influxdb:latest  
    container_name: Influxdb
    ports:
      - "8086:8086"
    env_file:
      - 'env.influxdb'
    volumes:
      -  $PWD/docker/influxdb/data_influxdb:/var/lib/influxdb

  telegraf:
    image: telegraf:latest   
    container_name: Telegraf
    links:
      - influxdb
    volumes:
      -  $PWD/telegraf.conf:/etc/telegraf/telegraf.conf:ro
     # - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
  grafana:
    image: grafana/grafana:7.3.7     
    container_name: Grafana
    ports:
      - "3000:3000"
    env_file:
      - 'env.grafana'
    user: "0"
    links:
      - influxdb
    volumes:
      -  $PWD/docker/grafana/data_grafana:/var/lib/grafana


  portainer:
    image: portainer/portainer-ce
    container_name: Portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - '9000:9000'
      - '8000:8000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/docker/portainer/portainer_data:/data


  node-red:
    image: nodered/node-red:latest
    container_name: Node_Red
    restart: always
    environment:
      - TZ=Europe/Madrid
    ports:
      - "1880:1880"
    volumes:
     # - $PWD/docker/nodered/node-red-data:/data
      - node-red-data:/data
    networks:
      - node-red-net


  heimdall:
    image: ghcr.io/linuxserver/heimdall
    container_name: Heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - $PWD/docker/heimdall/appdata/config>:/config
    ports:
      - 8500:80
      - 6443:443

  NPM:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    container_name: Nginx_PM
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      
        

  db:
    image: jc21/mariadb-aria:latest
    container_name: MariaDB
    restart: always    
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - $PWD/mariadb/docker/mysql:/var/lib/mysql     
    
  adminer:
    image: adminer:latest
    container_name: AdminerDB
    restart: always
    ports:
      - 7777:8080


networks:
  node-red-net:


volumes:
  data_influxdb:
  data_grafana:
  telegraf.conf:
  portainer_data:
  node-red-data:
