version: "3"

services:
  influxdb:
    image: influxdb:latest
    container_name: InfluxDB
    restart: always
    ports:
      - '8086:8086'
    volumes:
      - /home/ubuntu/docker/influx/influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=iiot
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
    networks:
      - DockerLAN
  telegraf:
    image: telegraf
    links:
      - influxdb
    volumes:
      # Mount for telegraf config
      -  ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    
    environment: 
      - DOCKER_INFLUXDB_INIT_ORG=myorg
      - DOCKER_INFLUXDB_INIT_BUCKET=mybucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken
    depends_on:
      - influxdb
    networks:
      - DockerLAN
           
  portainer:
    image: portainer/portainer-ce
    container_name: Portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - '9000:9000'
      - '8000:8000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ubuntu/portainer/portainer_data:/data
    networks:
      - DockerLAN          
  
  grafana:
    image: grafana/grafana:latest
    container_name: Grafana
    restart: always
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
      - /home/ubuntu/docker/grafana/grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}     
    networks:
      - DockerLAN
      
  node-red:
    image: nodered/node-red:latest
    container_name: Node_Red
    restart: always
    environment:
      - TZ=Europe/Madrid
    ports:
      - "1880:1880"
    volumes:
      - /home/ubuntu/docker/nodered/node-red-data:/data
    networks:
      - DockerLAN
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - DockerLAN      

  db:
    image: 'jc21/mariadb-aria:latest'
    restart: always    
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - /home/ubuntu/docker/mysql:/var/lib/mysql     
    networks:
      - DockerLAN

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - 7777:8080
    networks:
      - DockerLAN


  heimdall:
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/ubuntu/docker/heimdall/appdata/config>:/config
    ports:
      - 8500:80
      - 6443:443
    networks:
      - DockerLAN

  plex:
    container_name: plex
    hostname: Plex
    image: rapejim/pms-plexdrive-docker:arm64 
    restart: unless-stopped
    privileged: true
    network_mode: bridge
    ports: 
      - 32400:32400
    volumes:
      - /home/ubuntu/docker/plex/config:/config
      - /home/ubuntu/docker/plex/transcode:/transcode 
    environment:
      TZ: 'Europe/Madrid'
      EXTRA_PARAMS: '--drive-id=0ADJDLjjsHjA7Uk9PVA'
      PLEX_UID : '1000'
      PLEX_GID : '1000'
      # PLEX_CLAIM: XXXXXXXXXXXXXXXXXXXXXXXXXX # Optional -> https://www.plex.tv/claim/
    cap_add:
      - MKNOD
      - SYS_ADMIN
    devices:
      - '/dev/fuse'
      
volumes:
  influxdb-storage:
  grafana-storage:
  node-red-data:  
  portainer_data:

networks:
  DockerLAN:  ## Red bridge propia ##
    name: DockerLAN
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24  

