version: '2'

services:

  influxdb:
    image: influxdb:latest  
    container_name: influxdb
    ports:
      - "8086:8086"
    env_file:
      - 'env.influxdb'
    volumes:
      -  $PWD/docker/influxdb/data_influxdb:/var/lib/influxdb

  telegraf:
    image: telegraf:latest   
    container_name: telegraf
    links:
      - influxdb
    volumes:
      -  $PWD/docker/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
     # - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
  grafana:
    image: grafana/grafana:7.3.7     
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - 'env.grafana'
    user: "0"
    links:
      - influxdb
    volumes:
      -  $PWD/docker/grafana/data_grafana:/var/lib/grafana


  portainer:
    image: portainer/portainer-ce
    container_name: Portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - '9000:9000'
      - '8000:8000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/docker/portainer/portainer_data:/data


  node-red:
    image: nodered/node-red:latest
    container_name: Node_Red
    restart: always
    environment:
      - TZ=Europe/Madrid
    ports:
      - "1880:1880"
    volumes:
      - $PWD/docker/nodered/node-red-data:/data




  heimdall:
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - $PWD/docker/heimdall/appdata/config>:/config
    ports:
      - 8500:80
      - 6443:443



volumes:
  data_influxdb:
  data_grafana:
  telegraf.conf:
  portainer_data:
 
